### ISSUE TITLE
Package is not working on Android. When i call this method   await GoogleCastContext.instance.setSharedInstanceWithOptions(options!);

### ISSUE THREAD

**Issue by SaviCalidig** [felnanuke2/flutter_google_cast#1]
E/flutter (24429): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
E/flutter (24429): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/flutter (24429): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/flutter (24429): 	... 19 more
E/flutter (24429): )
E/flutter (24429): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (24429): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (24429): <asynchronous suspension>
E/flutter (24429): #2      GoogleCastContextAndroidMethodChannel.setSharedInstanceWithOptions (package:flutter_chrome_cast/_google_cast_context/android_google_cast_context_method_channel.dart:15:11)
E/flutter (24429): <asynchronous suspension>
E/flutter (24429): #3      DettaglioVideoController.initPlatformState (package:yoga/app/modules/home/controllers/dettaglio_video_controller.dart:53:5)
E/flutter (24429): <asynchronous suspension>
E/flutter (24429): #4      DettaglioVideoController.onInit (package:yoga/app/modules/home/controllers/dettaglio_video_controller.dart:37:5)
E/flutter (24429): <asynchronous suspension>
E/flutter (24429): 
 getting this error

**Comment by felnanuke2** [comment]
Hello,

Thank you for reaching out to us regarding the issue you're facing on GitHub. In order to assist you effectively, we kindly request that you provide us with the following information:

    Minimum Reproducible Code: It would be immensely helpful if you could share a minimum reproducible code snippet or a GitHub repository link that highlights the problem you are encountering. This will enable us to understand the issue better and provide you with an appropriate solution.

    Flutter Doctor Output: Please provide the output of the flutter doctor command. Running this command in your terminal will give us valuable insights into the status of your Flutter installation, including any potential issues or dependencies that need attention.

    Android Manifest.xml: If your issue is specifically related to Android, kindly share the contents of your Android manifest.xml file. This file contains important configuration details for your Flutter application, and examining it can help us identify any potential problems.

Once you provide us with these details, we'll be able to investigate the issue more thoroughly and provide you with the best possible solution. Thank you for your cooperation, and we look forward to assisting you further.

**Comment by felnanuke2** [comment]
Thank you for providing the reproducible code and addressing the issue in your package's GitHub repository. To rectify the problem with the missing update in the `androidManifest.xml` file, you can add the following code snippet:

```xml
<meta-data
    android:name="com.google.android.gms.cast.framework.OPTIONS_PROVIDER_CLASS_NAME"
    android:value="com.felnanuke.google_cast.GoogleCastOptionsProvider" />
```

Make sure to include this code within the `<application>` tag of your `androidManifest.xml` file. This addition will update the `androidManifest.xml` file to include the necessary `<meta-data>` element for `com.google.android.gms.cast.framework.OPTIONS_PROVIDER_CLASS_NAME`, using the value `"com.felnanuke.google_cast.GoogleCastOptionsProvider"`.

After incorporating this change, the issue related to the missing update in the `androidManifest.xml` should be resolved.
